remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: TOYT
description: Small Group Tuition for Primary School Science and Math / Secondary School Chemistry in Singapore
show_headers: true